packages:
  - 'packages/**'
  - 'tooling/**'

catalogs:
  dev:
    eslint: ^9.28.0
    prettier: ^3.6.0
    typescript: ^5.8.3
    '@types/node': ^22.15.29
    '@pixpilot/dev-config': ^1.6.2
    vitest: ^3.2.4
    '@vitest/ui': ^3.2.4
    '@vitest/coverage-v8': ^3.2.4
    'rollup': ^4.9.4
